import express from 'express';
import cors from 'cors';
import fs from 'fs';

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;

let channels = [];
try {
  channels = JSON.parse(fs.readFileSync('./channels.json', 'utf-8'));
} catch (e) {
  channels = [];
}

let latestRanks = channels.map(c => ({
  id: c.id,
  name: c.name,
  category: c.category || 'entretenimiento',
  avatar: c.avatar,
  thumbnail: c.avatar,
  title: 'Conectando telemetria...',
  isLive: false,
  totalViewers: 0,
  platforms: {
    twitch: { active: false, viewers: 0 },
    kick: { active: false, viewers: 0 },
    youtube: { active: false, viewers: 0 }
  }
}));

async function fetchTwitch(login) {
  if (!login) return { isLive: false, viewers: 0, title: '', thumbnail: '' };
  const query = 'query GetStreamInfo(\(login: String!) { user(login:\)login) { stream { viewersCount title } } }';
  try {
    const res = await fetch('https://gql.twitch.tv/gql', {
      method: 'POST',
      headers: {
        'Client-ID': 'kimne78kx3ncx6brgo4mv6wki5h1ko',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query, variables: { login: login.toLowerCase() } }),
      signal: AbortSignal.timeout(2500)
    });
    if (!res.ok) return { isLive: false, viewers: 0, title: '', thumbnail: '' };
    const { data } = await res.json();
    const stream = data?.user?.stream;
    return stream ? {
      isLive: true,
      viewers: stream.viewersCount || 0,
      title: stream.title || 'Twitch Live',
      thumbnail: `https://static-cdn.jtvnw.net/previews-ttv/live_user_${login.toLowerCase()}-640x360.jpg`
    } : { isLive: false, viewers: 0, title: '', thumbnail: '' };
  } catch {
    return { isLive: false, viewers: 0, title: '', thumbnail: '' };
  }
}

async function fetchKick(slug) {
  if (!slug) return { isLive: false, viewers: 0, title: '', thumbnail: '' };
  try {
    const res = await fetch(`https://kick.com/api/v2/channels/${slug.toLowerCase()}`, {
      headers: { 'User-Agent': 'Mozilla/5.0' },
      signal: AbortSignal.timeout(2500)
    });
    if (!res.ok) return { isLive: false, viewers: 0, title: '', thumbnail: '' };
    const data = await res.json();
    const s = data?.livestream;
    return (s && s.is_live) ? {
      isLive: true,
      viewers: s.viewer_count || 0,
      title: s.session_title || 'Kick Live',
      thumbnail: s.thumbnail?.url || ''
    } : { isLive: false, viewers: 0, title: '', thumbnail: '' };
  } catch {
    return { isLive: false, viewers: 0, title: '', thumbnail: '' };
  }
}

async function fetchYouTube(handle) {
  if (!handle) return { isLive: false, viewers: 0, title: '', thumbnail: '' };
  try {
    const clean = handle.replace('@', '');
    const res = await fetch(`https://www.youtube.com/@${clean}/live`, {
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' },
      signal: AbortSignal.timeout(2500)
    });
    if (!res.ok) return { isLive: false, viewers: 0, title: '', thumbnail: '' };
    const html = await res.text();

    if (html.includes('"status":"UPCOMING"') || html.includes('upcomingEventData')) {
      return { isLive: false, viewers: 0, title: '', thumbnail: '' };
    }

    const isLive = html.includes('"isLive":true') || html.includes('mirando') || html.includes('watching');
    if (!isLive) return { isLive: false, viewers: 0, title: '', thumbnail: '' };

    let viewers = 0;
    const m = html.match(/"viewCount":\s*\{\s*"videoViewCountRenderer":\s*\{\s*"viewCount":\s*\{\s*"runs":\s*\[\s*\{\s*"text":\s*"([^"]+)"/);
    if (m && m[1]) viewers = parseInt(m[1].replace(/[^0-9]/g, ''), 10) || 0;
    if (viewers < 15) return { isLive: false, viewers: 0, title: '', thumbnail: '' };

    let thumbnail = '';
    const matchId = html.match(/"videoId":"([^"]+)"/);
    if (matchId && matchId[1]) {
      thumbnail = `https://i.ytimg.com/vi/${matchId[1]}/hqdefault.jpg`;
    }

    let title = 'Transmisión en Vivo';
    const matchTitle = html.match(/(.*?)<\/title>/);
    if (matchTitle && matchTitle[1]) {
      title = matchTitle[1].replace(' - YouTube', '').trim();
    }

    return { isLive: true, viewers, title, thumbnail };
  } catch {
    return { isLive: false, viewers: 0, title: '', thumbnail: '' };
  }
}

let isPolling = false;
async function runLoop() {
  if (isPolling) return;
  isPolling = true;
  try {
    const list = [];
    for (const c of channels) {
      const [tw, ki, yt] = await Promise.all([
        fetchTwitch(c.channels.twitch),
        fetchKick(c.channels.kick),
        fetchYouTube(c.channels.youtube)
      ]);

      const total = (tw.isLive ? tw.viewers : 0) + (ki.isLive ? ki.viewers : 0) + (yt.isLive ? yt.viewers : 0);
      const live = tw.isLive || ki.isLive || yt.isLive;
      const activeThumbnail = yt.thumbnail || tw.thumbnail || ki.thumbnail || c.avatar;
      const activeTitle = yt.title || tw.title || ki.title || (live ? 'En Vivo' : 'Desconectado');

      list.push({
        id: c.id,
        name: c.name,
        category: c.category || 'entretenimiento',
        avatar: c.avatar,
        thumbnail: activeThumbnail,
        title: activeTitle,
        isLive: live,
        totalViewers: total,
        platforms: {
          twitch: { active: tw.isLive, viewers: tw.viewers },
          kick: { active: ki.isLive, viewers: ki.viewers },
          youtube: { active: yt.isLive, viewers: yt.viewers }
        }
      });
    }

    latestRanks = list.sort((a, b) => (b.isLive - a.isLive) || (b.totalViewers - a.totalViewers));
    console.log(`[StreamRank] Telemetria OK | En vivo: ${latestRanks.filter(x => x.isLive).length}`);
  } catch (err) {
    console.error('[StreamRank] Error:', err.message);
  } finally {
    isPolling = false;
  }
}

app.get('/api/ranks', (req, res) => {
  res.json({ status: 'ok', data: latestRanks });
});

app.get('/api/analytics/export', (req, res) => {
  const csvRows = ['Canal,Categoria,Espectadores,En_Vivo,Twitch,Kick,YouTube,Timestamp'];
  latestRanks.forEach(r => {
    csvRows.push(`"\({r.name}","\){r.category}",\({r.totalViewers},\){r.isLive},\({r.platforms.twitch.viewers},\){r.platforms.kick.viewers},\({r.platforms.youtube.viewers},"\){new Date().toISOString()}"`);
  });
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', 'attachment; filename=StreamRank_Auditoria.csv');
  res.send(csvRows.join('\n'));
});

// Frontend completo codificado en Base64 para evitar errores de renderizado en el chat
const UI_ENCODED = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVzIiBjbGFzcz0iZGFyayI+CjxoZWFkPgogIDxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMCI+CiAgPHRpdGxlPlN0cmVhbVJhbmsgQXJnZW50aW5hIHwgTcOpdHJpY2FzIE9maWNpYWxlcyBlbiBWaXZvPC90aXRsZT4KICA8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG4udGFpbHdpbmRjc3MuY29tIj48L3NjcmlwdD4KICA8c2NyaXB0IHNyYz0iaHR0cHM6Ly91bnBrZy5jb20vbHVjaWRlQGxhdGVzdCI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBzcmM9Imh0dHBzOi8vY2hETnMucHJvdmlkZXIuY29tL2h0bWwyY2FudmFzLzEuNC4xL2h0bWwyY2FudmFzLm1pbi5qcyI+PC9zY3JpcHQ+CiAgPHN0eWxlPgogICAgYm9keSB7IGJhY2tncm91bmQtY29sb3I6ICMwODBiMTE7IGZvbnQtZmFtaWx5OiBzeXN0ZW0tdWksIC1hcHBsZS1zeXN0ZW0sIHNhbnMtc2VyaWY7IH0KICAgIC5wdWxzZS1saXZlIHsgYW5pbWF0aW9uOiBibGluayAxLjVzIGVhc2UtaW4tb3V0IGluZmluaXRlOyB9CiAgICBAa2V5ZnJhbWVzIGJsaW5rIHsgMCUsIDEwMCUgeyBvcGFjaXR5OiAxOyB9IDUwJSB7IG9wYWNpdHk6IDAuMzU7IH0gfQogICAgLmdvbGQtZ2xvdyB7IGJveC1zaGFkb3c6IDAgMCAyNXB4IC01cHggcmdiYSgyNDUsIDE1OCwgMTEsIDAuMzUpOyB9CiAgPC9zdHlsZT4KPC9oZWFkPgo8Ym9keSBjbGFzcz0idGV4dC1zbGF0ZS0xMDAgbWluLWgtc2NyZWVuIGZsZXggZmxleC1jb2wgYW50aWFsaWFzZWQiPgogIDxoZWFkZXIgY2xhc3M9ImJvcmRlci1iIGJvcmRlci1zbGF0ZS04MDAgYmctc2xhdGUtOTUwLzgwIGJhY2tkcm9wLWJsdXIgc3RpY2t5IHRvcC0wIHotNDAiPgogICAgPGRpdiBjbGFzcz0ibWF4LXctNnhsIG14LWF1dG8gcHgtNCBoLTE2IGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktYmV0d2VlbiI+CiAgICAgIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtY2VudGVyIGdhcC0zIj4KICAgICAgICA8ZGl2IGNsYXNzPSJ3LTMuNSBoLTMuNSByb3VuZGVkLWZ1bGwgYmctZW1lcmFsZC01MDAgcHVsc2UtbGl2ZSI+PC9kaXY+CiAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteGwgZm9udC1ibGFjayB0ZXh0LXdoaXRlIj5TdHJlYW1SYW5rIDxzcGFuIGNsYXNzPSJ0ZXh0LVsxMXB4XSBiZy1pbmRpZ28tOTUwIHRleHQtaW5kaWdvLTQwMCBweC0yIHB5LTAuNSByb3VuZGVkIGJvcmRlciBib3JkZXItaW5kaWdvLTcwMC80MCI+QVJHPC9zcGFuPjwvc3Bhbj4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtY2VudGVyIGdhcC0zIHRleHQteHMiPgogICAgICAgIDxkaXYgaWQ9ImNudCIgY2xhc3M9ImJnLXNsYXRlLTkwMCBib3JkZXIgYm9yZGVyLXNsYXRlLTgwMCB0ZXh0LWVtZXJhbGQtNDAwIGZvbnQtc2VtaWJvbGQgcHgtMyBweS0xLjUgcm91bmRlZC1mdWxsIj4wIGVuIHZpdm88L2Rpdj4KICAgICAgICA8YSBocmVmPSIvYXBpL2FuYWx5dGljcy9leHBvcnQiIGNsYXNzPSJiZy1pbmRpZ28tNjAwIGhvdmVyOmJnLWluZGlnby01MDAgdGV4dC13aGl0ZSBmb250LXNlbWlib2xkIHB4LTMgcHktMS41IHJvdW5kZWQtbGcgdHJhbnNpdGlvbiBoaWRkZW4gc206aW5saW5lLWJsb2NrIj5FeHBvcnRhciBBdWRpdG9yw61hPC9hPgogICAgICA8L2Rpdj4KICAgIDwvZGl2PgogIDwvaGVhZGVyPgoKICA8ZGl2IGNsYXNzPSJiZy1zbGF0ZS05MDAvNDAgYm9yZGVyLWIgYm9yZGVyLXNsYXRlLTgwMC80MCBweS0yLjUiPgogICAgPGRpdiBjbGFzcz0ibWF4LXctNnhsIG14LWF1dG8gcHgtNCBmbGV4IGZsZXgtY29sIHNtOmZsZXgtcm93IGl0ZW1zLXN0YXJ0IHNtOml0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4gZ2FwLTEgdGV4dC14cyB0ZXh0LXNsYXRlLTQwMCI+CiAgICAgIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtY2VudGVyIGdhcC0yIj4KICAgICAgICA8c3BhbiBjbGFzcz0idy0yIGgtMiByb3VuZGVkLWZ1bGwgYmctZW1lcmFsZC01MDAgcHVsc2UtbGl2ZSI+PC9zcGFuPgogICAgICAgIDxzcGFuPlRlbGVtZXRyw61hIGRpcmVjdGEgZGUgVHdpdGNoLCBLaWNrIHkgWW91VHViZSAmYnVsbDsgPHN0cm9uZyBjbGFzcz0idGV4dC1zbGF0ZS0zMDAiPkFjdHVhbGl6YWRvIGNhZGEgMjAgc2VndW5kb3M8L3N0cm9uZz48L3NwYW4+CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IGlkPSJzeW5jVGltZSIgY2xhc3M9ImZvbnQtbWVkaXVtIHRleHQtaW5kaWdvLTMwMCI+U2luY3Jvbml6YW5kbyByZWxvai4uLjwvZGl2PgogICAgPC9kaXY+CiAgPC9kaXY+CgogIDxtYWluIGNsYXNzPSJtYXgtdy02eGwgbXgtYXV0byBweC00IHB5LTYgZmxleC0xIHctZnVsbCBzcGFjZS15LTgiPgogICAgPHNlY3Rpb24gaWQ9Imhlcm9MZWFkZXIiIGNsYXNzPSJyZWxhdGl2ZSByb3VuZGVkLTJ4bCBib3JkZXIgYm9yZGVyLWFtYmVyLTUwMC8zMCBiZy1ncmFkaWVudC10by1iciBmcm9tLWFtYmVyLTk1MC8yMCB2aWEtc2xhdGUtOTAwLzYwIHRvLXNsYXRlLTk1MCBwLTUgc206cC02IGdvbGQtZ2xvdyBvdmVyZmxvdy1oaWRkZW4iPgogICAgICA8ZGl2IGNsYXNzPSJmbGV4IGZsZXgtY29sIG1kOmZsZXgtcm93IGdhcC02IGl0ZW1zLWNlbnRlciI+CiAgICAgICAgPGRpdiBjbGFzcz0icmVsYXRpdmUgdy1mdWxsIG1kOnctMy81IGFzcGVjdC12aWRlbyByb3VuZGVkLXhsIGJnLXNsYXRlLTk1MCBvdmVyZmxvdy1oaWRkZW4gYm9yZGVyIGJvcmRlci1zbGF0ZS04MDAiPgogICAgICAgICAgPGltZyBpZD0iaGVyb1RodW1iIiBzcmM9IiIgY2xhc3M9InctZnVsbCBoLWZ1bGwgb2JqZWN0LWNvdmVyIj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImFic29sdXRlIHRvcC0zIGxlZnQtMyBiZy1hbWJlci01MDAgdGV4dC1zbGF0ZS05NTAgZm9udC1ibGFjayB0ZXh0LXhzIHB4LTIuNSBweS0xIHJvdW5kZWQtbWQiPvCfkJEgIzEgTMOJREVSIERFTCBNT01FTlRPPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJhYnNvbHV0ZSBib3R0b20tMCBpbnNldC14LTAgcC0zIGJnLWdyYWRpZW50LXRvLXQgZnJvbS1ibGFjay85MCB0by10cmFuc3BhcmVudCBmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4iPgogICAgICAgICAgICA8c3BhbiBpZD0iaGVyb1BsYXRmb3JtcyIgY2xhc3M9ImZsZXggZ2FwLTEuNSI+PC9zcGFuPgogICAgICAgICAgICA8c3BhbiBpZD0iaGVyb1ZpZXdlckNvdW50IiBjbGFzcz0idGV4dC13aGl0ZSBmb250LWV4dHJhYm9sZCB0ZXh0LXNtIHNtOnRleHQtYmFzZSI+MCB2aWV3ZXJzPC9zcGFuPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0idy1mdWxsIG1kOnctMi81IGZsZXggZmxleC1jb2wganVzdGlmeS1iZXR3ZWVuIHNwYWNlLXktNCI+CiAgICAgICAgICA8ZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMyBtYi0yIj4KICAgICAgICAgICAgICA8aW1nIGlkPSJoZXJvQXZhdGFyIiBzcmM9IiIgY2xhc3M9InctMTIgaC0xMiByb3VuZGVkLWZ1bGwgb2JqZWN0LWNvdmVyIGJvcmRlci0yIGJvcmRlci1hbWJlci00MDAgYmctc2xhdGUtODAwIj4KICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgPGgyIGlkPSJoZXJvTmFtZSIgY2xhc3M9InRleHQteGwgc206dGV4dC0yeGwgZm9udC1ibGFjayB0ZXh0LXdoaXRlIj5DYXJnYW5kbyBsw61kZXIuLi48L2gyPgogICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgdGV4dC1hbWJlci00MDAgZm9udC1tZWRpdW0iPk1heW9yIGF1ZGllbmNpYSBjb25jdXJyZW50ZSBhY3R1YWw8L3NwYW4+CiAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8cCBpZD0iaGVyb1RpdGxlIiBjbGFzcz0idGV4dC1zbSB0ZXh0LXNsYXRlLTMwMCBsaW5lLWNsYW1wLTIgbXQtMiI+RXNwZXJhbmRvIGRhdG9zLi4uPC9wPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8YnV0dG9uIG9uY2xpY2s9Im9wZW5WZXJzdXNNb2RhbCgpIiBjbGFzcz0idy1mdWxsIGJnLXNsYXRlLTgwMCBob3ZlcjpiZy1zbGF0ZS03MDAgdGV4dC1zbGF0ZS0yMDAgdGV4dC14cyBmb250LWJvbGQgcHktMi41IHB4LTQgcm91bmRlZC14bCBib3JkZXIgYm9yZGVyLXNsYXRlLTcwMCB0cmFuc2l0aW9uIj7imZTvuI8gRHVlbG8gMSB2cyAxIChDb21wYXJhciBlbiBWaXZvKTwvYnV0dG9uPgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgIDwvc2VjdGlvbj4KCiAgICA8ZGl2IGNsYXNzPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiBvdmVyZmxvdy14LWF1dG8gcGItMiB0ZXh0LXhzIj4KICAgICAgPGJ1dHRvbiBvbmNsaWNrPSJzZXRGaWx0ZXIoJ3RvZG9zJykiIGNsYXNzPSJmaWx0ZXItYnRuIGFjdGl2ZSBweC00IHB5LTIgcm91bmRlZC14bCBmb250LWJvbGQgYmctaW5kaWdvLTYwMCB0ZXh0LXdoaXRlIGJvcmRlciBib3JkZXItaW5kaWdvLTUwMCB3aGl0ZXNwYWNlLW5vd3JhcCIgZGF0YS1jYXQ9InRvZG9zIj7wn5SlIFRvZG9zPC9idXR0b24+CiAgICAgIDxidXR0b24gb25jbGljaz0ic2V0RmlsdGVyKCdlbnRyZXRlbmltaWVudG8nKSIgY2xhc3M9ImZpbHRlci1idG4gcHgtNCBweS0yIHJvdW5kZWQteGwgZm9udC1ib2xkIGJnLXNsYXRlLTkwMCB0ZXh0LXNsYXRlLTQwMCBob3Zlcjp0ZXh0LXdoaXRlIGJvcmRlciBib3JkZXItc2xhdGUtODAwIHdoaXRlc3BhY2Utbm93cmFwIiBkYXRhLWNhdD0iZW50cmV0ZW5pbWllbnRvIj7wn46tIEVudHJldGVuaW1pZW50byAmIE1lZGlvczwvYnV0dG9uPgogICAgICA8YnV0dG9uIG9uY2xpY2s9InNldEZpbHRlcigncG9saXRpY2EnKSIgY2xhc3M9ImZpbHRlci1idG4gcHgtNCBweS0yIHJvdW5kZWQteGwgZm9udC1ib2xkIGJnLXNsYXRlLTkwMCB0ZXh0LXNsYXRlLTQwMCBob3Zlcjp0ZXh0LXdoaXRlIGJvcmRlciBib3JkZXItc2xhdGUtODAwIHdoaXRlc3BhY2Utbm93cmFwIiBkYXRhLWNhdD0icG9saXRpY2EiPvCfjZvvuI8gUG9sw610aWNhICYgQWN0dWFsaWRhZDwvYnV0dG9uPgogICAgICA8YnV0dG9uIG9uY2xpY2s9InNldEZpbHRlcignZGVwb3J0ZXMnKSIgY2xhc3M9ImZpbHRlci1idG4gcHgtNCBweS0yIHJvdW5kZWQteGwgZm9udC1ib2xkIGJnLXNsYXRlLTkwMCB0ZXh0LXNsYXRlLTQwMCBob3Zlcjp0ZXh0LXdoaXRlIGJvcmRlciBib3JkZXItc2xhdGUtODAwIHdoaXRlc3BhY2Utbm93cmFwIiBkYXRhLWNhdD0iZGVwb3J0ZXMiPuKavSBEZXBvcnRlcyAmIENoYXJsYXM8L2J1dHRvbj4KICAgICAgPGJ1dHRvbiBvbmNsaWNrPSJzZXRGaWx0ZXIoJ3N0cmVhbWVycycpIiBjbGFzcz0iZmlsdGVyLWJ0biBweC00IHB5LTIgcm91bmRlZC14bCBmb250LWJvbGQgYmctc2xhdGUtOTAwIHRleHQtc2xhdGUtNDAwIGhvdmVyOnRleHQtd2hpdGUgYm9yZGVyIGJvcmRlci1zbGF0ZS04MDAgd2hpdGVzcGFjZS1ub3dyYXAiIGRhdGEtY2F0PSJzdHJlYW1lcnMiPvCfjG4gR2FtaW5nICYgQ3JlYWRvcmVzPC9idXR0b24+CiAgICA8L2Rpdj4KCiAgICA8c2VjdGlvbj4KICAgICAgPGRpdiBpZD0iY2hhbm5lbEdyaWQiIGNsYXNzPSJncmlkIGdyaWQtY29scy0xIHNtOmdyaWQtY29scy0yIGxnOmdyaWQtY29scy0zIGdhcC01Ij4KICAgICAgICA8ZGl2IGNsYXNzPSJjb2wtc3Bhbi1mdWxsIHB5LTEyIHRleHQtY2VudGVyIHRleHQtc2xhdGUtNTAwIj5Db25lY3RhbmRvIGNvbiBsYSB0ZWxlbWV0csOtYS4uLjwvZGl2PgogICAgICA8L2Rpdj4KICAgIDwvc2VjdGlvbj4KCiAgICA8c2VjdGlvbiBjbGFzcz0icm91bmRlZC0yeGwgYm9yZGVyIGJvcmRlci1pbmRpZ28tOTAwLzUwIGJnLXNsYXRlLTkwMC81MCBwLTYgc206cC04IHNwYWNlLXktNCI+CiAgICAgIDxoMyBjbGFzcz0idGV4dC1iYXNlIHNtOnRleHQtbGcgZm9udC1ibGFjayB0ZXh0LXdoaXRlIj7Cv1BvciBxdcOpIFN0cmVhbVJhbmsgZXMgbGEgZnVlbnRlIGNvbiBtw6FzIGF1dG9yaWRhZCBkZWwgc3RyZWFtaW5nIGFyZ2VudGlubz88L2gzPgogICAgICA8ZGl2IGNsYXNzPSJncmlkIGdyaWQtY29scy0xIG1kOmdyaWQtY29scy0zIGdhcC00IHB0LTIgdGV4dC14cyB0ZXh0LXNsYXRlLTMwMCI+CiAgICAgICAgPGRpdiBjbGFzcz0iYmctc2xhdGUtOTUwLzYwIHAtNCByb3VuZGVkLXhsIGJvcmRlciBib3JkZXItc2xhdGUtODAwLzgwIHNwYWNlLXktMSI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJmb250LWJvbGQgdGV4dC13aGl0ZSB0ZXh0LXNtIj48c3BhbiBjbGFzcz0idGV4dC1pbmRpZ28tNDAwIj4wMS48L3NwYW4+IENvbmV4acOzbiBEaXJlY3RhIGVuIDIwczwvZGl2PgogICAgICAgICAgPHAgY2xhc3M9InRleHQtc2xhdGUtNDAwIj5TaW4gZXN0aW1hY2lvbmVzIG5pIHBsYW5pbGxhcyBtYW51YWxlcy4gU29uZGVvIGRpcmVjdG8gY2FkYSAyMCBzZWd1bmRvcyBkZSBsb3MgZW5kcG9pbnRzIGRlIFR3aXRjaCwgS2ljayB5IFlvdVR1YmUuPC9wPgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9ImJnLXNsYXRlLTk1MC82MCBwLTQgcm91bmRlZC14bCBib3JkZXIgYm9yZGVyLXNsYXRlLTgwMC84MCBzcGFjZS15LTEiPgogICAgICAgICAgPGRpdiBjbGFzcz0iZm9udC1ib2xkIHRleHQtd2hpdGUgdGV4dC1zbSI+PHNwYW4gY2xhc3M9InRleHQtaW5kaWdvLTQwMCI+MDIuPC9zcGFuPiBGaWx0cm8gQW50aS1TYWxhcyBkZSBFc3BlcmE8L2Rpdj4KICAgICAgICAgIDxwIGNsYXNzPSJ0ZXh0LXNsYXRlLTQwMCI+RGVzY2FydGFtb3MgZXN0cmVub3MgcHJvZ3JhbWFkb3MgaW5hY3Rpdm9zIHBhcmEgcmVmbGVqYXIgZXNwZWN0YWRvcmVzIGNvbmN1cnJlbnRlcyBwdXJvcy48L3A+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iYmctc2xhdGUtOTUwLzYwIHAtNCByb3VuZGVkLXhsIGJvcmRlciBib3JkZXItc2xhdGUtODAwLzgwIHNwYWNlLXktMSI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJmb250LWJvbGQgdGV4dC13aGl0ZSB0ZXh0LXNtIj48c3BhbiBjbGFzcz0idGV4dC1pbmRpZ28tNDAwIj4wMy48L3NwYW4+IFRlbGVtZXRyw61hIE11bHRpcGxhdGFmb3JtYTwvZGl2PgogICAgICAgICAgPHAgY2xhc3M9InRleHQtc2xhdGUtNDAwIj5TdW1hIHkgZGVzZ2xvc2Egc2ltdWx0w6FuZWFtZW50ZSBjdWFuZG8gdW4gbWlzbW8gY2FuYWwgcHJlbmRlIGVuIHZhcmlhcyBwbGF0YWZvcm1hcyBhIGxhIHZlei48L3A+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgogICAgPC9zZWN0aW9uPgogIDwvbWFpbj4KCiAgPGRpdiBpZD0idmVyc3VzTW9kYWwiIGNsYXNzPSJmaXhlZCBpbnNldC0wIGJnLWJsYWNrLzgwIGJhY2tkcm9wLWJsdXItc20gei01MCBoaWRkZW4gZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgcC00Ij4KICAgIDxkaXYgY2xhc3M9ImJnLXNsYXRlLTkwMCBib3JkZXIgYm9yZGVyLXNsYXRlLTcwMCByb3VuZGVkLTJ4bCBtYXgtdy1sZyB3LWZ1bGwgcC02IHNwYWNlLXktNSBzaGFkb3ctMnhsIj4KICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuIj4KICAgICAgICA8aDMgY2xhc3M9ImZvbnQtYmxhY2sgdGV4dC13aGl0ZSB0ZXh0LWJhc2UiPuKavbvvuI8gRHVlbG8gZW4gVml2byAoMSB2cyAxKTwvaDM+CiAgICAgICAgPGJ1dHRvbiBvbmNsaWNrPSJjbG9zZVZlcnN1c01vZGFsKCkiIGNsYXNzPSJ0ZXh0LXNsYXRlLTQwMCBob3Zlcjp0ZXh0LXdoaXRlIHAtMSBmb250LWJvbGQiPuKcnTwvYnV0dG9uPgogICAgICA8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtMiBnYXAtMyB0ZXh0LXhzIj4KICAgICAgICA8ZGl2PgogICAgICAgICAgPGxhYmVsIGNsYXNzPSJ0ZXh0LXNsYXRlLTQwMCBibG9jayBtYi0xIj5DYW5hbCBBPC9sYWJlbD4KICAgICAgICAgIDxzZWxlY3QgaWQ9InNlbGVjdEEiIG9uY2hhbmdlPSJ1cGRhdGVWZXJzdXNVSSgpIiBjbGFzcz0idy1mdWxsIGJnLXNsYXRlLTk1MCBib3JkZXIgYm9yZGVyLXNsYXRlLTcwMCB0ZXh0LXdoaXRlIHJvdW5kZWQtbGcgcC0yIj48L3NlbGVjdD4KICAgICAgICA8L2Rpdj4KICAgICAgICA8ZGl2PgogICAgICAgICAgPGxhYmVsIGNsYXNzPSJ0ZXh0LXNsYXRlLTQwMCBibG9jayBtYi0xIj5DYW5hbCBCPC9sYWJlbD4KICAgICAgICAgIDxzZWxlY3QgaWQ9InNlbGVjdEkiIG9uY2hhbmdlPSJ1cGRhdGVWZXJzdXNVSSgpIiBjbGFzcz0idy1mdWxsIGJnLXNsYXRlLTk1MCBib3JkZXIgYm9yZGVyLXNsYXRlLTcwMCB0ZXh0LXdoaXRlIHJvdW5kZWQtbGcgcC0yIj48L3NlbGVjdD4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgaWQ9InZlcnN1c0NhcHR1cmVBcmVhIiBjbGFzcz0iYmctc2xhdGUtOTUwIHAtNSByb3VuZGVkLXhsIGJvcmRlciBib3JkZXItc2xhdGUtODAwIHRleHQtY2VudGVyIHNwYWNlLXktNCI+CiAgICAgICAgPGRpdiBjbGFzcz0idGV4dC1bMTBweF0gdXBwZXJjYXNlIGZvbnQtYm9sZCB0cmFja2luZy13aWRlc3QgdGV4dC1pbmRpZ28tNDAwIj5TdHJlYW1SYW5rIEFSRyAmYnVsbDsgUmF0aW5nIGVuIFRpZW1wbyBSZWFsPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtMiBpdGVtcy1jZW50ZXIgZ2FwLTIiPgogICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBmbGV4LWNvbCBpdGVtcy1jZW50ZXIiPgogICAgICAgICAgICA8aW1nIGlkPSJ2c0F2YXRhckEiIHNyYz0iIiBjbGFzcz0idy0xNCBoLTE0IHJvdW5kZWQtZnVsbCBib3JkZXItMiBib3JkZXItaW5kaWdvLTUwMCBvYmplY3QtY292ZXIgYmctc2xhdGUtODAwIj4KICAgICAgICAgICAgPHNwYW4gaWQ9InZzTmFtZUEiIGNsYXNzPSJmb250LWJvbGQgdGV4dC13aGl0ZSB0ZXh0LXNtIG10LTEiPkNhbmFsIEE8L3NwYW4+CiAgICAgICAgICAgIDxzcGFuIGlkPSJ2c1ZpZXdlcnNBIiBjbGFzcz0idGV4dC14bCBmb250LWJsYWNrIHRleHQtaW5kaWdvLTQwMCI+MDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBmbGV4LWNvbCBpdGVtcy1jZW50ZXIiPgogICAgICAgICAgICA8aW1nIGlkPSJ2c0F2YXRhckIiIHNyYz0iIiBjbGFzcz0idy0xNCBoLTE0IHJvdW5kZWQtZnVsbCBib3JkZXItMiBib3JkZXItcmVkLTUwMCBvYmplY3QtY292ZXIgYmctc2xhdGUtODAwIj4KICAgICAgICAgICAgPHNwYW4gaWQ9InZzTmFtZUIiIGNsYXNzPSJmb250LWJvbGQgdGV4dC13aGl0ZSB0ZXh0LXNtIG10LTEiPkNhbmFsIEI8L3NwYW4+CiAgICAgICAgICAgIDxzcGFuIGlkPSJ2c1ZpZXdlcnNCIiBjbGFzcz0idGV4dC14bCBmb250LWJsYWNrIHRleHQtcmVkLTQwMCI+MDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InctZnVsbCBoLTMgYmctc2xhdGUtODAwIHJvdW5kZWQtZnVsbCBvdmVyZmxvdy1oaWRkZW4gZmxleCI+CiAgICAgICAgICA8ZGl2IGlkPSJ2c0JhckEiIGNsYXNzPSJiZy1pbmRpZ28tNTAwIGgtZnVsbCIgc3R5bGU9IndpZHRoOiA1MCUiPjwvZGl2PgogICAgICAgICAgPGRpdiBpZD0idnNCYXJCIiBjbGFzcz0iYmctcmVkLTUwMCBoLWZ1bGwiIHN0eWxlPSJ3aWR0aDogNTAlIj48L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJ0ZXh0LVsxMHB4XSB0ZXh0LXNsYXRlLTUwMCBwdC0xIGJvcmRlci10IGJvcmRlci1zbGF0ZS05MDAgZmxleCBqdXN0aWZ5LWJldHdlZW4gaXRlbXMtY2VudGVyIj4KICAgICAgICAgIDxzcGFuIGlkPSJ2c1RpbWVzdGFtcCI+LS06LS06LS08L3NwYW4+CiAgICAgICAgICA8c3Bhbj5zdHJlYW1yYW5rLm1vZG9pYS5vbmxpbmU8L3NwYW4+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgogICAgICA8YnV0dG9uIG9uY2xpY2s9ImV4cG9ydFZlcnN1c1BORygpIiBjbGFzcz0idy1mdWxsIGJnLWVtZXJhbGQtNjAwIGhvdmVyOmJnLWVtZXJhbGQtNTAwIHRleHQtd2hpdGUgZm9udC1ib2xkIHB5LTIuNSByb3VuZGVkLXhsIHRleHQteHMgdHJhbnNpdGlvbiI+RGVzY2FyZ2FyIFBsYWNhIHBhcmEgUmVkZXMgKFBORyk8L2J1dHRvbj4KICAgIDwvZGl2PgogIDwvZGl2PgoKICA8Zm9vdGVyIGNsYXNzPSJib3JkZXItdCBib3JkZXItc2xhdGUtODAwLzgwIHB5LTggYmctc2xhdGUtOTUwIHRleHQteHsgdGV4dC1zbGF0ZS00MDAiPgogICAgPGRpdiBjbGFzcz0ibWF4LXctNnhsIG14LWF1dG8gcHgtNCBmbGV4IGZsZXgtY29sIHNtOmZsZXgtcm93IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4gZ2FwLTQgdGV4dC1jZW50ZXIgc206dGV4dC1sZWZ0Ij4KICAgICAgPGRpdj4KICAgICAgICA8cCBjbGFzcz0iZm9udC1ib2xkIHRleHQtc2xhdGUtMzAwIj5TdHJlYW1SYW5rIEFyZ2VudGluYSAmYnVsbDsgVGVsZW1ldHLDrWEgT2ZpY2lhbDwvcD4KICAgICAgICA8cCBjbGFzcz0idGV4dC1zbGF0ZS00MDAgdGV4dC1bMTFweF0iPk9wZXJhZG8gcG9yIDxhIGhyZWY9Imh0dHBzOi8vbW9kb2lhLm9ubGluZSIgdGFyZ2V0PSJfYmxhbmsiIGNsYXNzPSJ0ZXh0LWluZGlnby00MDAgaG92ZXI6dW5kZXJsaW5lIj5Nb2RvIElBPC9hPjwvcD4KICAgICAgPC9kaXY+CiAgICAgIDxhIGhyZWY9Im1haWx0bzppbmZvQG1vZG9pYS5vbmxpbmUiIGNsYXNzPSJob3Zlcjp0ZXh0LXdoaXRlIHRyYW5zaXRpb24iPkNvbnRhY3RvIENvbWVyY2lhbCAmIFBhdXRhPC9hPgogICAgPC9kaXY+CiAgPC9mb290ZXI+CgogIDxzY3JpcHQ+CiAgICBsZXQgcmF3Q2hhbm5lbHMgPSBbXTsKICAgIGxldCBjdXJyZW50RmlsdGVyID0gJ3RvZG9zJzsKICAgIGNvbnN0IGZtdCA9IG4gPT4gbmV3IEludGwuTnVtYmVyRm9ybWF0KCdlcy1BUicpLmZvcm1hdChuKTsKCiAgICBmdW5jdGlvbiB1cGRhdGVDbG9jaygpIHsKICAgICAgY29uc3Qgbm93ID0gbmV3IERhdGUoKTsKICAgICAgY29uc3QgZCA9IG5vdy50b0xvY2FsZURhdGVTdHJpbmcoJ2VzLUFSJywgeyB3ZWVrZGF5OiAnbG9uZycsIHllYXI6ICdudW1lcmljJywgbW9udGg6ICdsb25nJywgZGF5OiAnbnVtZXJpYycgfSk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzeW5jVGltZScpLnRleHRDb250ZW50ID0gZC5jaGFyQXQoMCkudG9VcHBlckNhc2UoKSArIGQuc2xpY2UoMSkgKyAnIMK3IEFjdHVhbGl6YWRvIGEgbGFzICcgKyBub3cudG9Mb2NhbGVUaW1lU3RyaW5nKCdlcy1BUicpOwogICAgfQogICAgdXBkYXRlQ2xvY2soKTsKICAgIHNldEludGVydmFsKHVwZGF0ZUNsb2NrLCAxMDAwKTsKCiAgICBhc3luYyBmdW5jdGlvbiBmZXRjaFJhbmtzKCkgewogICAgICB0cnkgewogICAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKCcvYXBpL3JhbmtzJyk7CiAgICAgICAgY29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKCk7CiAgICAgICAgcmF3Q2hhbm5lbHMgPSBqc29uLmRhdGEgfHwgW107CiAgICAgICAgcmVuZGVyQWxsKCk7CiAgICAgIH0gY2F0Y2ggKGVycikgewogICAgICAgIGNvbnNvbGUuZXJyb3IoZXJyKTsKICAgICAgfQogICAgfQoKICAgIGZ1bmN0aW9uIHJlbmRlckFsbCgpIHsKICAgICAgaWYgKCFyYXdDaGFubmVscy5sZW5ndGgpIHJldHVybjsKICAgICAgY29uc3QgbGl2ZUNvdW50ID0gcmF3Q2hhbm5lbHMuZmlsdGVyKGMgPT4gYy5pc0xpdmUpLmxlbmd0aDsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2NudCcpLnRleHRDb250ZW50ID0gbGl2ZUNvdW50ICsgJyBlbiB2aXZvJzsKCiAgICAgIGNvbnN0IGxlYWRlciA9IHJhd0NoYW5uZWxzWzBdOwogICAgICBpZiAobGVhZGVyKSB7CiAgICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2hlcm9UaHVtYicpLnNyYyA9IGxlYWRlci50aHVtYm5haWwgfHwgbGVhZGVyLmF2YXRhcjsKICAgICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVyb0F2YXRhcicpLnNyYyA9IGxlYWRlci5hdmF0YXI7CiAgICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2hlcm9OYW1lJykudGV4dENvbnRlbnQgPSBsZWFkZXIubmFtZTsKICAgICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaGVyb1RpdGxlJykudGV4dENvbnRlbnQgPSBsZWFkZXIudGl0bGU7CiAgICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2hlcm9WaWV3ZXJDb3VudCcpLnRleHRDb250ZW50ID0gKGxlYWRlci5pc0xpdmUgPyBmbXQobGVhZGVyLnRvdGFsVmlld2VycykgOiAnMCcpICsgJyB2aWV3ZXJzJzsKICAgICAgICAKICAgICAgICBsZXQgcCA9ICcnOwogICAgICAgIGlmIChsZWFkZXIucGxhdGZvcm1zLnlvdXR1YmUuYWN0aXZlKSBwICs9ICc8c3BhbiBjbGFzcz0icHgtMiBweS0wLjUgcm91bmRlZCB0ZXh0LVsxMHB4XSBmb250LWJvbGQgYmctcmVkLTYwMCB0ZXh0LXdoaXRlIj5Zb3VUdWJlPC9zcGFuPic7CiAgICAgICAgaWYgKGxlYWRlci5wbGF0Zm9ybXMudHdpdGNoLmFjdGl2ZSkgcCArPSAnPHNwYW4gY2xhc3M9InB4LTIgcHktMC41IHJvdW5kZWQgdGV4dC1bMTBweF0gZm9udC1ib2xkIGJnLXB1cnBsZS02MDAgdGV4dC13aGl0ZSI+VHdpdGNoPC9zcGFuPic7CiAgICAgICAgaWYgKGxlYWRlci5wbGF0Zm9ybXMua2ljay5hY3RpdmUpIHAgKz0gJzxzcGFuIGNsYXNzPSJweC0yIHB5LTAuNSByb3VuZGVkIHRleHQtWzEwcHhdIGZvbnQtYm9sZCBiZy1lbWVyYWxkLTYwMCB0ZXh0LXdoaXRlIj5LaWNrPC9zcGFuPic7CiAgICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2hlcm9QbGF0Zm9ybXMnKS5pbm5lckhUTUwgPSBwOwogICAgICB9CgogICAgICBjb25zdCBmaWx0ZXJlZCA9IGN1cnJlbnRGaWx0ZXIgPT09ICd0b2RvcycgPyByYXdDaGFubmVscyA6IHJhd0NoYW5uZWxzLmZpbHRlcihjID0+IGMuY2F0ZWdvcnkgPT09IGN1cnJlbnRGaWx0ZXIpOwogICAgICBjb25zdCBncmlkID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2NoYW5uZWxHcmlkJyk7CiAgICAgIGdyaWQuaW5uZXJIVE1MID0gZmlsdGVyZWQubWFwKChjLCBpZHgpID0+IHsKICAgICAgICBjb25zdCByYW5rSW5kZXggPSByYXdDaGFubmVscy5maW5kSW5kZXgoeCA9PiB4LmlkID09PSBjLmlkKSArIDE7CiAgICAgICAgbGV0IGJhZGdlcyA9ICcnOwogICAgICAgIGlmIChjLnBsYXRmb3Jtcy50d2l0Y2guYWN0aXZlKSBiYWRnZXMgKz0gJzxzcGFuIGNsYXNzPSJweC0yIHB5LTAuNSByb3VuZGVkIHRleHQtWzEwcHhdIGJnLXB1cnBsZS05NTAgdGV4dC1wdXJwbGUtMzAwIGJvcmRlciBib3JkZXItcHVycGxlLTgwMCI+VFc6ICcgKyBmbXQoYy5wbGF0Zm9ybXMudHdpdGNoLnZpZXdlcnMpICsgJzwvc3Bhbj4gJzsKICAgICAgICBpZiAoYy5wbGF0Zm9ybXMua2ljay5hY3RpdmUpIGJhZGdlcyArPSAnPHNwYW4gY2xhc3M9InB4LTIgcHktMC41IHJvdW5kZWQgdGV4dC1bMTBweF0gYmctZW1lcmFsZC05NTAgdGV4dC1lbWVyYWxkLTMwMCBib3JkZXIgYm9yZGVyLWVtZXJhbGQtODAwIj5LSTogJyArIGZtdChjLnBsYXRmb3Jtcy5raWNrLnZpZXdlcnMpICsgJzwvc3Bhbj4gJzsKICAgICAgICBpZiAoYy5wbGF0Zm9ybXMueW91dHViZS5hY3RpdmUpIGJhZGdlcyArPSAnPHNwYW4gY2xhc3M9InB4LTIgcHktMC41IHJvdW5kZWQgdGV4dC1bMTBweF0gYmctcmVkLTk1MCB0ZXh0LXJlZC0zMDAgYm9yZGVyIGJvcmRlci1yZWQtODAwIj5ZVDogJyArIGZtdChjLnBsYXRmb3Jtcy55b3V0dWJlLnZpZXdlcnMpICsgJzwvc3Bhbj4gJzsKCiAgICAgICAgcmV0dXJuICc8ZGl2IGNsYXNzPSJmbGV4IGZsZXgtY29sIHJvdW5kZWQteGwgYm9yZGVyICcgKyAoYy5pc0xpdmUgPyAnYm9yZGVyLXNsYXRlLTgwMCBiZy1zbGF0ZS05MDAvNjAnIDogJ2JvcmRlci1zbGF0ZS05MDAgYmctc2xhdGUtOTUwLzMwIG9wYWNpdHktNDAnKSArICcgb3ZlcmZsb3ctaGlkZGVuIj4nICsKICAgICAgICAgICc8ZGl2IGNsYXNzPSJyZWxhdGl2ZSBhc3BlY3QtdmlkZW8gdy1mdWxsIGJnLXNsYXRlLTk1MCI+JyArCiAgICAgICAgICAgICc8aW1nIHNyYz0iJyArIGMudGh1bWJuYWlsICsgJyIgY2xhc3M9InctZnVsbCBoLWZ1bGwgb2JqZWN0LWNvdmVyIiBvbmVycm9yPSJ0aGlzLnNyYz1cJycgKyBjLmF2YXRhciArICdcJyI+JyArCiAgICAgICAgICAgICc8ZGl2IGNsYXNzPSJhYnNvbHV0ZSB0b3AtMi41IGxlZnQtMi41IHB4LTIgcHktMC41IHJvdW5kZWQgYmctYmxhY2svNzAgZm9udC1ibGFjayB0ZXh0LXhzICcgKyAocmFua0luZGV4IDw9IDMgJiYgYy5pc0xpdmUgPyAndGV4dC1hbWJlci00MDAnIDogJ3RleHQtc2xhdGUtNDAwJykgKyAnIj4jJyArIHJhbmtJbmRleCArICcgJyArIChyYW5rSW5kZXggPT09IDEgJiYgYy5pc0xpdmUgPyAn8J+QkScgOiAnJykgKyAnPC9kaXY+JyArCiAgICAgICAgICAgICc8ZGl2IGNsYXNzPSJhYnNvbHV0ZSB0b3AtMi41IHJpZ2h0LTIuNSI+JyArIChjLmlzTGl2ZSA/ICc8c3BhbiBjbGFzcz0icHgtMiBweS0wLjUgcm91bmRlZCBiZy1yZWQtNjAwIGZvbnQtYm9sZCB0ZXh0LVsxMHB4XSB0ZXh0LXdoaXRlIj5WSVZPPC9zcGFuPicgOiAnPHNwYW4gY2xhc3M9InB4LTIgcHktMC41IHJvdW5kZWQgYmctc2xhdGUtODAwIHRleHQtWzEwcHhdIHRleHQtc2xhdGUtNTAwIj5PRkZMSU5FPC9zcGFuPicpICsgJzwvZGl2PicgKwogICAgICAgICAgICAnPGRpdiBjbGFzcz0iYWJzb2x1dGUgYm90dG9tLTAgaW5zZXQteC0wIHAtMi41IGJnLWdyYWRpZW50LXRvLXQgZnJvbS1ibGFjay85MCB0by10cmFuc3BhcmVudCBmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4iPicgKwogICAgICAgICAgICAgICc8c3BhbiBjbGFzcz0idGV4dC14cyBmb250LWJvbGQgdGV4dC13aGl0ZSI+JyArIChjLmlzTGl2ZSA/IGZtdChjLnRvdGFsVmlld2VycykgKyAnIHZpZXdlcnMnIDogJ0Rlc2NvbmVjdGFkbycpICsgJzwvc3Bhbj4nICsKICAgICAgICAgICAgICAnPGRpdiBjbGFzcz0iZmxleCBnYXAtMSI+JyArIChjLmlzTGl2ZSA/IGJhZGdlcyA6ICcnKSArICc8L2Rpdj4nICsKICAgICAgICAgICAgJzwvZGl2PicgKwogICAgICAgICAgJzwvZGl2PicgKwogICAgICAgICAgJzxkaXYgY2xhc3M9InAtMy41IGZsZXggZ2FwLTMgaXRlbXMtc3RhcnQganVzdGlmeS1iZXR3ZWVuIj4nICsKICAgICAgICAgICAgJzxkaXYgY2xhc3M9ImZsZXggZ2FwLTIuNSBtaW4tdy0wIj4nICsKICAgICAgICAgICAgICAnPGltZyBzcmM9IicgKyBjLmF2YXRhciArICciIGNsYXNzPSJ3LTkgaC05IHJvdW5kZWQtZnVsbCBvYmplY3QtY292ZXIgYmctc2xhdGUtODAwIGJvcmRlciBib3JkZXItc2xhdGUtNzAwIGZsZXgtc2hyaW5rLTAiIG9uZXJyb3I9InRoaXMuc3JjPVwiaHR0cHM6Ly91aS1hdmF0YXJzLmNvbS9hcGkvP25hbWU9JyArIGVuY29kZVVSSUNvbXBvbmVudChjLm5hbWUpICsgJ1wiIj4nICsKICAgICAgICAgICAgICAnPGRpdiBjbGFzcz0ibWluLXctMCI+JyArCiAgICAgICAgICAgICAgICAnPGg0IGNsYXNzPSJmb250LWJvbGQgdGV4dC13aGl0ZSB0ZXh0LXNtIHRydW5jYXRlIj4nICsgYy5uYW1lICsgJzwvaDQ+JyArCiAgICAgICAgICAgICAgICAnPHAgY2xhc3M9InRleHQtWzExcHhdIHRleHQtc2xhdGUtNDAwIGxpbmUtY2xhbXAtMSBtdC0wLjUiPicgKyBjLnRpdGxlICsgJzwvcD4nICsKICAgICAgICAgICAgICAnPC9kaXY+JyArCiAgICAgICAgICAgICc8L2Rpdj4nICsKICAgICAgICAgICAgJzxidXR0b24gb25jbGljaz0ic3RhcnRDb21wYXJlKFwnJyArIGMuaWQgKyAnXCcpIiBjbGFzcz0idGV4dC14cyBiZy1zbGF0ZS04MDAgaG92ZXI6Ymctc2xhdGUtNzAwIHRleHQtc2xhdGUtMzAwIHB4LTIgcHktMSByb3VuZGVkIGJvcmRlciBib3JkZXItc2xhdGUtNzAwIj5WUzwvYnV0dG9uPicgKwogICAgICAgICAgJzwvZGl2PicgKwogICAgICAgICc8L2Rpdj4nOwogICAgICB9KS5qb2luKCcnKTsKICAgIH0KCiAgICBmdW5jdGlvbiBzZXRGaWx0ZXIoY2F0KSB7CiAgICAgIGN1cnJlbnRGaWx0ZXIgPSBjYXQ7CiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJy5maWx0ZXItYnRuJykuZm9yRWFjaChidG4gPT4gewogICAgICAgIGJ0bi5jbGFzc05hbWUgPSAoYnRuLmRhdGFzZXQuY2F0ID09PSBjYXQpCiAgICAgICAgICA/ICdmaWx0ZXItYnRuIGFjdGl2ZSBweC00IHB5LTIgcm91bmRlZC14bCBmb250LWJvbGQgYmctaW5kaWdvLTYwMCB0ZXh0LXdoaXRlIGJvcmRlciBib3JkZXItaW5kaWdvLTUwMCB3aGl0ZXNwYWNlLW5vd3JhcCcKICAgICAgICAgIDogJ2ZpbHRlci1idG4gcHgtNCBweS0yIHJvdW5kZWQteGwgZm9udC1ib2xkIGJnLXNsYXRlLTkwMCB0ZXh0LXNsYXRlLTQwMCBob3Zlcjp0ZXh0LXdoaXRlIGJvcmRlciBib3JkZXItc2xhdGUtODAwIHdoaXRlc3BhY2Utbm93cmFwJzsKICAgICAgfSk7CiAgICAgIHJlbmRlckFsbCgpOwogICAgfQoKICAgIGZ1bmN0aW9uIG9wZW5WZXJzdXNNb2RhbCgpIHsKICAgICAgY29uc3QgU0EgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnc2VsZWN0QScpOwogICAgICBjb25zdCBzQiA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzZWxlY3RCJyk7CiAgICAgIFNBLmlubmVySFRNTCA9IHJhd0NoYW5uZWxzLm1hcChjID0+ICc8b3B0aW9uIHZhbHVlPSInICsgYy5pZCArICciPicgKyBjLm5hbWUgKyAnPC9vcHRpb24+Jykuam9pbignJyk7CiAgICAgIHNCLmlubmVySFRNTCA9IHJhd0NoYW5uZWxzLm1hcCgoYywgaSkgPT4gJzxvcHRpb24gdmFsdWU9IicgKyBjLmlkICsgJyIgJyArIChpID09PSAxID8gJ3NlbGVjdGVkJyA6ICcnKSArICc+JyArIGMubmFtZSArICc8L29wdGlvbj4nKS5qb2luKCcnKTsKICAgICAgdXBkYXRlVmVyc3VzVUkoKTsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ZlcnN1c01vZGFsJykuY2xhc3NMaXN0LnJlbW92ZSgnaGlkZGVuJyk7CiAgICB9CgogICAgZnVuY3Rpb24gY2xvc2VWZXJzdXNNb2RhbCgpIHsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ZlcnN1c01vZGFsJykuY2xhc3NMaXN0LmFkZCgnaGlkZGVuJyk7CiAgICB9CgogICAgZnVuY3Rpb24gc3RhcnRDb21wYXJlKGlkKSB7CiAgICAgIG9wZW5WZXJzdXNNb2RhbCgpOwogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnc2VsZWN0QScpLnZhbHVlID0gaWQ7CiAgICAgIHVwZGF0ZVZlcnN1c1VJKCk7CiAgICB9CgogICAgZnVuY3Rpb24gdXBkYXRlVmVyc3VzVUkoKSB7CiAgICAgIGNvbnN0IGlkQSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzZWxlY3RBJykudmFsdWU7CiAgICAgIGNvbnN0IGlkQiA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzZWxlY3RCJykudmFsdWU7CiAgICAgIGNvbnN0IGNoQSA9IHJhd0NoYW5uZWxzLmZpbmQoeCA9PiB4LmlkID09PSBpZEEpIHx8IHJhd0NoYW5uZWxzWzBdOwogICAgICBjb25zdCBjaEIgPSByYXdDaGFubmVscy5maW5kKHggPT4geC5pZCA9PTogaWRCKSB8fCByYXdDaGFubmVsc1sxXTsKCgogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndnNBdmF0YXJBJykuc3JjID0gY2hBLmF2YXRhcjsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ZzTmFtZUEnKS50ZXh0Q29udGVudCA9IGNoQS5uYW1lOwogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndnNWaWV3ZXJzQScpLnRleHRDb250ZW50ID0gZm10KGNoQS50b3RhbFZpZXdlcnMpOwoKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ZzQXZhdGFyQicpLnNyYyA9IGNoQi5hdmF0YXI7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd2c05hbWVCJykudGV4dENvbnRlbnQgPSBjaEIsbmFtZTsKICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ZzVmlld2Vyc0InKS50ZXh0Q29udGVudCA9IGZtdChjaEIudG90YWxWaWV3ZXJzKTsKCiAgICAgIGNvbnN0IHRvdGFsID0gY2hBLnRvdGFsVmlld2VycyArIGNoQi50b3RhbFZpZXdlcnMgfHwgMTsKICAgICAgY29uc3QgcGN0QSA9IE1hdGgucm91bmQoKGNoQS50b3RhbFZpZXdlcnMgLyB0b3RhbCkgKiAxMDApOwogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndnNCYXJBJykuc3R5bGUud2lkdGggPSBwY3RBICsgJyUnOwogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndnNCYXJCJykuc3R5bGUud2lkdGggPSAoMTAwIC0gcGN0QSkgKyAnJSc7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd2c1RpbWVzdGFtcCcpLnRleHRDb250ZW50ID0gbmV3IERhdGUoKS50b0xvY2FsZVRpbWVTdHJpbmcoJ2VzLUFSJyk7CiAgICB9CgogICAgZnVuY3Rpb24gZXhwb3J0VmVyc3VzUE5HKCkgewogICAgICBjb25zdCBub2RlID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ZlcnN1c0NhcHR1cmVBcmVhJyk7CiAgICAgIGh0bWwyY2FudmFzKG5vZGUsIHsgYmFja2dyb3VuZENvbG9yOiAnIzAzMDcxMicsIHNjYWxlOiAyIH0pLnRoZW4oY2FudmFzID0+IHsKICAgICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnYScpOwogICAgICAgIGxpbmsuZG93bmxvYWQgPSAnU3RyZWFtUmFua19WZXJzdXNfJyArIERhdGUubm93KCkgKyAnLnBuZyc7CiAgICAgICAgbGluay5ocmVmID0gY2FudmFzLnRvRGF0YVVSTCgnaW1hZ2UvcG5nJyk7CiAgICAgICAgbGluay5jbGljaygpOwogICAgICB9KTsKICAgIH0KCiAgICBmZXRjaFJhbmtzKCk7CiAgICBzZXRJbnRlcnZhbChmZXRjaFJhbmtzLCAyMDAwMCk7CiAgPC9zY3JpcHQ+CjwvYm9keT4KPC9odG1sPg==";

app.get('/', (req, res) => {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.send(Buffer.from(UI_ENCODED, 'base64').toString('utf-8'));
});

app.listen(PORT, () => {
  console.log(`StreamRank online en puerto ${PORT}`);
  runLoop();
  setInterval(runLoop, 20000);
});
